name: Smoke Test Cardano Rosetta
description: Runs the image, waits, then performs a basic smoke test
inputs:
  cardano-rosetta-version:
    description: Software version
    required: false
    default: master
  network-identifier:
    description: Supported Cardano network
    required: false
    default: mainnet
runs:
  using: composite
  steps:
    - name: Run
      run: docker run --rm -d -p 8080:8080 --name cardano-rosetta cardano-rosetta:${{ inputs.cardano-rosetta-version }}
      shell: bash
    - name: Test
      run: |
        sleep 10
        curl -X POST -H "Content-Type: application/json" -d '{"network_identifier":{"blockchain": "cardano", "network":"${{ inputs.network-identifier }}"}}' http://localhost:8080/network/status
        docker stop cardano-rosetta
      shell: bash
