name: Smoke Test Cardano Rosetta
description: Runs the image, waits, then performs a basic smoke test
inputs:
  tag:
    description: Docker tag
    required: false
    default: latest
  network-identifier:
    description: Supported Cardano network
    required: false
    default: mainnet
  test-exe:
    description: Smoke test executable
    required: true
runs:
  using: composite
  steps:
    - name: Run
      run: docker run --rm -d -p 8080:8080 --name cardano-rosetta-smoke-test --shm-size=2g cardano-rosetta:${{ inputs.tag }}
      shell: bash
    - name: Test
      run: |
        sleep 10
        ${{ inputs.test-exe }} ${{ inputs.network-identifier }}
        docker stop cardano-rosetta
      shell: bash
