name: Build Cardano Rosetta
description: Builds the Dockerfile using a remote cache
inputs:
  cardano-rosetta-version:
    description: Software version
    required: false
    default: master
  network-identifier:
    description: Supported Cardano network
    required: false
    default: mainnet
  build-cache-image:
    description: From the Docker registry, including tag
    required: false
    default: inputoutput/cardano-rosetta:master
runs:
  using: composite
  steps:
    - name: Prepare tag name
      run: echo "::set-env name=tag::$(echo $version | sed -e 's/\//-/g')"
      shell: bash
      env:
        version: ${{ inputs.cardano-rosetta-version }}
    - name: Build remote Dockerile using cache
      run: wget --secure-protocol=TLSv1_2
          -O- https://raw.githubusercontent.com/input-output-hk/cardano-rosetta/${{ inputs.cardano-rosetta-version }}/Dockerfile
          | docker build
            --build-arg BUILDKIT_INLINE_CACHE=1
            --build-arg CARDANO_ROSETTA_VERSION=${{ inputs.cardano-rosetta-version }}
            --build-arg NETWORK=${{ inputs.network-identifier }}
            --cache-from ${{ inputs.build-cache-image }}
            -t cardano-rosetta:$tag
            -
      shell: bash
      env:
        DOCKER_BUILDKIT: 1
