name: Build Cardano Rosetta
description: Builds the Dockerfile using a remote cache
inputs:
  tag:
    description: Docker tag
    required: false
    default: latest
  network-identifier:
    description: Supported Cardano network
    required: false
    default: mainnet
  build-cache-image:
    description: From the Docker registry, including tag
    required: false
    default: cardanofoundation/cardano-rosetta:master
  build-context:
    description: Mapped to the docker build command
    required: true
runs:
  using: composite
  steps:
    - name: Build image with inline cache
      run: docker build
        --build-arg BUILDKIT_INLINE_CACHE=1
        --build-arg NETWORK=${{ inputs.network-identifier }}
        --cache-from ${{ inputs.build-cache-image }}
        -t cardano-rosetta:${{ inputs.tag }}
        ${{ inputs.build-context }}
      shell: bash
      env:
        DOCKER_BUILDKIT: 1
