name: API-test

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Start-container
        run: docker run --rm -d -p 8080:8080 cardano-rosetta:${{ github.sha }}
      - name: Wait for docker to start
        run: sleep 60
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'
      - name: "Install newman"
        run: npm install -g newman
      - name: "Run tests"
        working-directory: ./cardano-rosetta
        run: newman run ./test/deployed-environment-test/rosetta-java.postman_collection.json -e ./test/deployed-environment-test/environments/mainnet-typescript.postman_environment.json -r cli